### ISSUE TITLE
The option to automatically resize the bar

### ISSUE THREAD

**Issue by conxr** [blahsd/supernerd.widget#11]
Would this be possible? Sometimes I'll plug into my ultrawide, so had it set to that width in default.css & it threw out the centering

<img width="1680" alt="screen shot 2018-03-06 at 13 15 55" src="https://user-images.githubusercontent.com/31190088/37034801-5df2e09a-2142-11e8-9bd5-3c60f624ff0b.png">

Easy fix to switch it back, but automatically adjusting would be cool

**Comment by blahsd** [comment]
The bar should now always be at 100% of the screen. Let me know if it's working, and thanks for signalling!
