### ISSUE TITLE
Playing output displaying incorrectly

### ISSUE THREAD

**Issue by conxr** [blahsd/supernerd.widget#12]
Not sure what's happening, but the track info is displaying below the bar for me

<img width="1000" alt="screen shot 2018-03-06 at 13 28 49" src="https://user-images.githubusercontent.com/31190088/37034977-f2146910-2142-11e8-8f64-1b45e212b44a.png">

**Comment by blahsd** [comment]
This was an issue that I had, but I thought I had fixed it. Can you make sure that you have the latest version downloaded? If you need to replicate the issue, it used to happened when the title of the song was wider than its container, so pick songs with long names 😛

Here is what should happen in the last version (the name gets truncated):
<img width="1920" alt="screenshot 2018-03-06 15 01 15" src="https://user-images.githubusercontent.com/7347353/37036320-94bc50d6-214f-11e8-9b3f-41ea920ef505.png">

By the way, thank you for taking the time to point out all of these issues. It's extremely helpful, and will make this tool a much better one, I think!

**Comment by conxr** [comment]
That's fixed it!

It might have been my fault, I may have been lazy and overwritten the default.css with my old one.

Or maybe I had the font size too large in .widg, .playing-output {
As I just noticed playing around that I could recreate it by setting it to 11px

However, my bottom bar has now gone transparent after reinstalling, is there a way to fix this?

<img width="1680" alt="screen shot 2018-03-06 at 15 10 54" src="https://user-images.githubusercontent.com/31190088/37039951-97139b68-2150-11e8-82eb-29db7fdfba26.png">

And no worries on the feedback, glad to be helping someone putting in such hard work!

**Comment by blahsd** [comment]
Fixed! I'm afraid I'd fucked it up while fixing the length hahaha
