### ISSUE TITLE
Error: ./supernerd.widget/lib/weather.txt no file or directory

### ISSUE THREAD

**Issue by CobreDev** [blahsd/supernerd.widget#19]
I am getting an error that says No file or directory:  ./supernerd.widget/lib/weather.txt. I have a screenshot for more.
![screen shot 2018-03-14 at 11 22 17](https://user-images.githubusercontent.com/36574329/37411924-5134dd3e-277a-11e8-8fd8-3ae4fb1f9b04.png)

**Comment by blahsd** [comment]
Hi! Mistake on my part – the weather widget isn't ready (it's not working as intended yet), and I must have included it in my commit by mistake. Just as a quick workaround, to get rid of the error, in your supernerd.widget folder create a folder named lib; then, inside that folder, create an empty text file called weather.txt. I'll fix this up later in the day. Sorry for the mishap and let me know if it works.

**Comment by CobreDev** [comment]
Ok...It was giving me a few errors, figured it out. When you are installing Supernerd, the command needs to be `git clone https://github.com/blahsd/supernerd.widget $HOME/Library/Application\ Support/Übersicht/widgets/supernerd.widget` instead of `git clone https://github.com/blahsd/supernerd.widget $HOME/Library/Application\ Support/Übersicht/widgets`

**Comment by blahsd** [comment]
Ah, thanks! Must be something with my setup. I'll update the readme right now!
