### ISSUE TITLE
Shows up, but not clickable

### ISSUE THREAD

**Issue by CobreDev** [blahsd/supernerd.widget#20]
I finally got it to work (sort of) but I cant click on anything.

**Comment by blahsd** [comment]
Great! The thing about clicking is that Ubersicht sits *behind* your rendered desktop. Unfortunately I have no control over this. If you want to enable seamless interaction with supernerd, there instructions in the readme, I'll copy them here: 

> 
> Lucky for you, in order to use all of the interactive shit, you must renounce interacting with your desktop icons. I know, I know. But since using your desktop like a 'put shit here' folder is not a good idea, this might actually help you. Do so: [defaults write com.apple.finder CreateDesktop -bool FALSE;killall Finder](url)
> 
> When you're ready to revert back to your barbarian-like usage of your desktop/dumpster, do this: `defaults delete com.apple.finder CreateDesktop;killall Finder`
> 
> 

If you'd rather not do that, everything will be clickable only when you are holding down your selected Ubersicht modifier key. I think the predefined key is fn, but you can change that in the Ubersicht preference panel

**Comment by CobreDev** [comment]
Ok thanks
